mybatis:
  #POJO??????
  type-aliases-package: com.wzl.market.pojo
  #mapper.xml?????
  mapper-locations: classpath:/mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Market?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1
    redis:
      host: 127.0.0.1
      password:
      port: 6379
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 1000

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml